var fs=require('fs');
const data00 = " {\n"
const data01 = "    " + "\"name\": " + "\"git-pull-cron-mod\",\n"
const data02 = "    " + "\"version\": " + "\"1.0.0\",\n"
const data03 = "    " + "\"description\": " + "\"Modified version of the tool that will git clone a repo into a folder and schedule a cron job to pull updates\",\n"
const data04 = "    " + "\"main\": " + "\"index.js\",\n"
const data05 = "    " + "\"scripts\"" + ": {\n"
const data06 = "      " + "\"test\": " + "\"grunt\",\n"
const data07 = "    },\n"
const data08 = "    " + "\"repository\"" + ": {\n"
const data09 = "      " + "\"type\": " + "\"git\",\n"
const data10 = "      " + "\"url\": " + "\"https://github.com/WiiLink24-Extensions/cron.js.git\"" + "\n"
const data11 = "    },\n"
const data12 = "    " + "\"keywords\"" + ": [\n"
const data13 = "      " + "\"git\",\n"
const data14 = "      " + "\"cron\"" + "\n"
const data15 = "    ],\n"
const data16 = "   " + "\"author\": " + "\"Ramesh Nair <ram@hiddentao.com> & Mod by 6100m\",\n"
const data17 = "   " + "\"license\": " + "\"MIT\",\n"
const data18 = "   " + "\"bugs\"" + ": {\n"
const data19 = "     " + "\"url\": " + "\"https://github.com/WiiLink24-Extensions/cron.jsissues\"" + "\n"
const data20 = "   },\n"
const data21 = "   " + "\"homepage\": " + "\"https://github.com/WiiLink24-Extensions/cron.js",\n"
const data22 = "   " + "\"dependencies\"" + ": {\n"
const data23 = "     " + "\"debug\": " + "\"~4.1.1\",\n"
const data24 = "     " + "\"rimraf\": " + "\"~2.2.8\",\n"
const data25 = "     " + "\"cron\": " + "\"~1.0.4\",\n"
const data26 = "     " + "\"gift\": " + "\"~0.4.1\",\n"
const data27 = "     " + "\"bluebird\": " + "\"~1.2.4\"" + "\n"
const data28 = "   },\n"
const data29 = "   " + "\"devDependencies\"" + ": {\n"
const data30 = "     " + "\"grunt\": " + "\"~0.4.5\",\n"
const data31 = "     " + "\"grunt-mocha-test\": " + "\"~0.11.0\",\n"
const data32 = "     " + "\"grunt-contrib-jshint\": " + "\"~0.10.0\",\n"
const data33 = "     " + "\"atchdep\": " + "\"~0.3.0\",\n"
const data34 = "     " + "\"chai\": " + "\"~1.9.1\",\n"
const data35 = "     " + "\"sinon\": " + "\"~1.10.2\",\n"
const data36 = "     " + "\"then-fs\": " + "\"~1.0.6\",\n"
const data37 = "     " + "\"chai-as-promised\": " + "\"~4.1.1\"" + "\n"
const data38 = "   }\n"
const data39 = " }\n"
const data40 = data00 + data01 + data02 + data03 + data04 + data05 + data06 + data07 + data08 + data09
const data41 = data10 + data11 + data12 + data13 + data14 + data15 + data16 + data17 + data18 + data19
const data42 = data20 + data21 + data22 + data23 + data24 + data25 + data26 + data27 + data28 + data29
const data43 = data30 + data31 + data32 + data33 + data34 + data35 + data36 + data37 + data38 + data39
const data44 = data40 + data41
const data45 = data42 + data43
const data46 = data44 + data45
const data47 = "package.json"
const data48 = " file..."
const data49 = " generated!"
fs.writeFile(data47, data46, function (err) {
  if (err) throw err;
  console.log(data47 + data48 + data49);
});
