var fs=require('fs');
const data00 = "{\n"
const data01 = "    // Settings\n"
const data02 = "    " + "\"passfail\"" + "      : false,  // Stop on first error.\n"
const data03 = "    " + "\"maxerr\"" + "        : 100,    // Maximum error before stopping.\n"
const data04 = "\n"
const data05 = "\n"
const data06 = "    // Predefined globals whom JSHint will ignore.\n"
const data07 = "    " + "\"browser\"" + "       : false,   // Standard browser globals e.g. `window`, `document`.\n"
const data08 = "\n"
const data09 = "    " + "\"node\"" + "          : true,\n"
const data10 = "    " + "\"rhino\"" + "         : false,\n"
const data11 = "    " + "\"couch\"" + "         : false,\n"
const data12 = "    " + "\"wsh\"" + "           : true,   // Windows Scripting Host.\n"
const data13 = "\n"
const data14 = "    " + "\"jquery\"" + "        : false,\n"
const data15 = "    " + "\"prototypejs\"" + "   : false,\n"
const data16 = "    " + "\"mootools\"" + "      : false,\n"
const data17 = "    " + "\"dojo\"" + "          : false,\n"
const data18 = "\n"
const data19 = "    " + "\"predef\"" + "        : [  // Custom globals.\n"
const data20 = "    ],\n"
const data21 = "\n"
const data22 = "\n"
const data23 = "    // Development.\n"
const data24 = "    " + "\"debug\"" + "         : false,  // Allow debugger statements e.g. browser breakpoints.\n"
const data25 = "    " + "\"devel\"" + "         : true,   // Allow developments statements e.g. `console.log();`.\n"
const data26 = "\n"
const data27 = "\n"
const data28 = "    // ECMAScript\n"
const data29 = "    " + "\"esnext\"" + "        : false,   // Using ES6\n"
const data30 = "    " + "\"noyield\"" + "       : false,   // allow generators with no yields\n"
const data31 = "    " + "\"strict\"" + "        : true,  // Require `use strict` pragma  in every file.\n"
const data32 = "    " + "\"globalstrict\"" + "  : false,  // Allow global " + "\"use strict\"" + " (also enables " + "\'strict\'" + ").\n"
const data33 = "\n"
const data34 = "    // The Good Parts.\n"
const data35 = "    " + "\"asi\"" + "           : true,  // Tolerate Automatic Semicolon Insertion (no semicolons).\n"
const data36 = "    " + "\"laxbreak\"" + "      : true,   // Tolerate unsafe line breaks e.g. `return [\\n] x` without semicolons.\n"
const data37 = "    " + "\"bitwise\"" + "       : true,   // Prohibit bitwise operators (&, |, ^, etc.).\n"
const data38 = "    " + "\"boss\"" + "          : false,  // Tolerate assignments inside if, for & while. Usually conditions & loops are for comparison, not assignments.\n"
const data39 = "    " + "\"curly\"" + "         : true,   // Require {} for every new block or scope.\n"
const data40 = "    " + "\"eqeqeq\"" + "        : true,   // Require triple equals i.e. `===`.\n"
const data41 = "    " + "\"eqnull\"" + "        : false,  // Tolerate use of `== null`.\n"
const data42 = "    " + "\"evil\"" + "          : false,  // Tolerate use of `eval`.\n"
const data43 = "    " + "\"expr\"" + "          : false,  // Tolerate `ExpressionStatement` as Programs.\n"
const data44 = "    " + "\"forin\"" + "         : false,  // Tolerate `for in` loops without `hasOwnPrototype`.\n"
const data45 = "    " + "\"immed\"" + "         : true,   // Require immediate invocations to be wrapped in parens e.g. `( function(){}() );`\n"
const data46 = "    " + "\"latedef\"" + "       : true,   // Prohipit variable use before definition.\n"
const data47 = "    " + "\"loopfunc\"" + "      : false,  // Allow functions to be defined within loops.\n"
const data48 = "    " + "\"noarg\"" + "         : true,   // Prohibit use of `arguments.caller` and `arguments.callee`.\n"
const data49 = "    " + "\"regexp\"" + "        : true,   // Prohibit `.` and `[^...]` in regular expressions.\n"
const data50 = "    " + "\"regexdash\"" + "     : false,  // Tolerate unescaped last dash i.e. `[-...]`.\n"
const data51 = "    " + "\"scripturl\"" + "     : true,   // Tolerate script-targeted URLs.\n"
const data52 = "    " + "\"shadow\"" + "        : false,  // Allows re-define variables later in code e.g. `var x=1; x=2;`.\n"
const data53 = "    " + "\"supernew\"" + "      : false,  // Tolerate `new function () { ... };` and `new Object;`.\n"
const data54 = "    " + "\"undef\"" + "         : true,   // Require all non-global variables be declared before they are used.\n"
const data55 = "    " + "\"newcap\"" + "        : true,   // Require capitalization of all constructor functions e.g. `new F()`.\n"
const data56 = "    " + "\"noempty\"" + "       : true,   // Prohibit use of empty blocks.\n"
const data57 = "    " + "\"nonew\"" + "         : true,   // Prohibit use of constructors for side-effects.\n"
const data58 = "    " + "\"nomen\"" + "         : false,   // Allow use of initial or trailing underbars in names.\n"
const data59 = "    " + "\"onevar\"" + "        : false,  // Allow only one `var` statement per function.\n"
const data60 = "    " + "\"plusplus\"" + "      : false,  // Prohibit use of `++` & `--`.\n"
const data61 = "    " + "\"sub\"" + "           : false,  // Tolerate all forms of subscript notation besides dot notation e.g. `dict['key']` instead of `dict.key`.\n"
const data62 = "    " + "\"trailing\"" + "      : true,   // Prohibit trailing whitespaces.\n"
const data63 = "    " + "\"white\"" + "         : false,  // Check against strict whitespace and indentation rules.\n"
const data64 = "    " + "\"indent\"" + "        : 2       // Specify indentation spacing\n"
const data65 = "}\n"
const data66 = data00 + data01 + data02 + data03 + data04 + data05 + data06 + data07 + data08 + data09
const data67 = data10 + data11 + data12 + data13 + data14 + data15 + data16 + data17 + data18 + data19
const data68 = data20 + data21 + data22 + data23 + data24 + data25 + data26 + data27 + data28 + data29
const data69 = data30 + data31 + data32 + data33 + data34 + data35 + data36 + data37 + data38 + data39
const data70 = data40 + data41 + data42 + data43 + data44 + data45 + data46 + data47 + data48 + data49
const data71 = data50 + data51 + data52 + data53 + data54 + data55 + data56 + data57 + data58 + data59
const data72 = data66 + data67
const data73 = data68 + data69
const data74 = data70 + data71
const data75 = data72 + data73
const data76 = data75 + data74
const data77 = "."
const data78 = "jshintrc"
const data79 = data77 + data78
fs.writeFile(data79, data76, function (err) {
  if (err) throw err;
  console.log(data79 + " file... generated!");
});
